import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import AppHeader from "@/components/header/app.header";
import NavbarMobile from "@/components/header/navbar.mobile";
import { Overlay } from "@radix-ui/react-dialog";
import AppFooter from "@/components/footer/app.footer";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
    title: "MangaNoob",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <AppHeader />
                {children}
                <NavbarMobile/>
                <AppFooter />
            </body>
        </html>
    );
}
